load("//javatests/jsinterop/generator:jsinterop_generator_test.bzl", "jsinterop_generator_test")

jsinterop_generator_test(
    name = "VarargUnionTest",
    srcs = ["vararg_union.js"],
    expected_output = glob(["*.java.txt"]),
)
