dist: xenial
sudo: required

os:
  - linux
  - osx

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      OS=darwin
    else
      sysctl kernel.unprivileged_userns_clone=1
      OS=linux
    fi

    BAZELISK_VERSION=v1.5.0
    if [ ! -d "${HOME}/bin" ]; then
      mkdir "${HOME}/bin"
    fi
    wget -O "${HOME}/bin/bazel" "https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-${OS}-amd64"
    chmod +x "${HOME}/bin/bazel"

before_script:
  - echo "startup --output_base=$HOME/.cache/bazel" >> .bazelrc
  # Avoid progress indicators that can blow out log which makes using WEB UI difficult
  - echo "common --noshow_progress" >> .bazelrc
  - echo "common --noshow_loading_progress" >> .bazelrc
  # This is so we understand failures better
  - echo "build --verbose_failures" >> .bazelrc

script: ./bazel_build_test.sh

notifications:
  email: false
