# Description:
#   JsInterop generator tests.

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//:__subpackages__"],
    licenses = ["notice"],
)

exports_files([
    "jsinterop_generator_test.sh",
])
