# Description:
#   JsInterop generator tests.

package(
    default_visibility = ["//:__subpackages__"],
    # Apache2
    licenses = ["notice"],
)

exports_files([
    "jsinterop_generator_test.sh",
])
